# Fill in with a valid world name
# ex:
# enable-world:
#  - world1
#  - world2
# disable-world:
#  - world3
# if it is not filled it means that all worlds are enabled

enable-world: []
disable-world:
  - world

message:
# if you want no message please replace it with "false"
# ex =  enable: false
  enable: true
# This message is sent when the message is enabled
# & for coloring
# {player} for the player name
  msg: "&aYou don't fall into void because anti void"